#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

PORTFOLIO_DIR="/Users/reynalddaffa/Vibe Coding/My First Porto"
cd "$PORTFOLIO_DIR" || { echo "Can't find $PORTFOLIO_DIR"; exit 1; }
ENV_FILE="$PORTFOLIO_DIR/case-study-app/.env"

banner "Contentful-backed case studies — go live"

# ── Stage 1: GitHub repo ───────────────────────────────────────────────────
stage "GitHub repo — create + push"
say "Your code is committed locally but has no home on GitHub yet."
BRANCH_NAME="main"
ask BRANCH_NAME "Branch to push as (main/master):"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "gh is installed and logged in — this can create the repo and push in one step."
  if confirm "Create public repo reynalddff/portfolio and push now?"; then
    git branch -M "$BRANCH_NAME"
    gh repo create reynalddff/portfolio --public --source=. --remote=origin --push
  else
    note "skipped — do it manually later (see below)."
  fi
else
  step "Open https://github.com/new, owner=reynalddff, name=portfolio, Public, no README/gitignore/license."
  open_url "https://github.com/new"
  pause "Press Enter once the empty repo exists on GitHub..."
  git branch -M "$BRANCH_NAME"
  git remote add origin https://github.com/reynalddff/portfolio.git 2>/dev/null || git remote set-url origin https://github.com/reynalddff/portfolio.git
  if confirm "Push local history to origin/$BRANCH_NAME now?"; then
    git push -u origin "$BRANCH_NAME"
  else
    note "skipped — run: git push -u origin $BRANCH_NAME"
  fi
fi

# ── Stage 2: GitHub Pages ──────────────────────────────────────────────────
stage "GitHub Pages — enable"
say "Turns the repo into a live site at https://reynalddff.github.io/portfolio/"
open_url "https://github.com/reynalddff/portfolio/settings/pages"
step "Under 'Build and deployment' → Source, choose 'Deploy from a branch'."
step "Branch: $BRANCH_NAME, folder: / (root). Save."
pause "Press Enter once saved (first deploy takes ~1 min)..."

# ── Stage 3: Contentful space ──────────────────────────────────────────────
stage "Contentful — create space"
say "This creates the space that holds your case-study content."
open_url "https://app.contentful.com/"
step "Log in (or sign up — free tier is enough for this)."
step "Create a new space — any name, e.g. 'portfolio'. Pick the free 'Community' plan."
step "Once inside the space: Settings → General settings, and copy the Space ID shown there."
pause "Press Enter once the space exists..."
CONTENTFUL_SPACE_ID=""
ask CONTENTFUL_SPACE_ID "Contentful Space ID:"

# ── Stage 4: content type — import caseStudy ───────────────────────────────
stage "Content type — import caseStudy"
say "contentful-schema/caseStudy.json has your case-study fields ready to go —"
say "the Contentful CLI imports it as a content type in one shot."
if ! command -v contentful >/dev/null 2>&1; then
  if confirm "contentful-cli not found — install it now (npm install -g contentful-cli)?"; then
    npm install -g contentful-cli
  else
    SKIPPED+=("install contentful-cli, then run: contentful space import --content-file contentful-schema/caseStudy.json --space-id $CONTENTFUL_SPACE_ID --environment-id master")
  fi
fi
if command -v contentful >/dev/null 2>&1; then
  say "This opens a browser login the first time (contentful login)."
  contentful login || true
  if confirm "Import contentful-schema/caseStudy.json into space $CONTENTFUL_SPACE_ID now?"; then
    contentful space import --content-file contentful-schema/caseStudy.json --space-id "$CONTENTFUL_SPACE_ID" --environment-id master
  else
    SKIPPED+=("run: contentful space import --content-file contentful-schema/caseStudy.json --space-id $CONTENTFUL_SPACE_ID --environment-id master")
  fi
else
  warn "skipping import — do it later with the command above."
fi

# ── Stage 5: API key — Content Delivery API ────────────────────────────────
stage "API key — Content Delivery API"
say "This is the read-only token the site uses to fetch published content."
say "Safe to embed client-side — it's Contentful's intended public-read token."
open_url "https://app.contentful.com/spaces/${CONTENTFUL_SPACE_ID}/api/keys"
step "Add API key (or use the auto-generated 'Example Key')."
step "Copy 'Content Delivery API - access token' from the key's detail page."
pause "Press Enter once you have the token..."
CONTENTFUL_ACCESS_TOKEN=""
ask_secret CONTENTFUL_ACCESS_TOKEN "Content Delivery API access token:"

# ── Stage 6: wire tokens into the app + homepage ───────────────────────────
stage "Tokens — wire into the app + homepage"
write_env "VITE_CONTENTFUL_SPACE_ID" "$CONTENTFUL_SPACE_ID"
write_env "VITE_CONTENTFUL_ENVIRONMENT" "master"
write_env "VITE_CONTENTFUL_ACCESS_TOKEN" "$CONTENTFUL_ACCESS_TOKEN"
say "homepage.js has no build step, so its Contentful config is plain strings —"
say "the space ID is not secret, but the access token is embedded the same way"
say "Contentful expects for client-side delivery reads."
if grep -q "your-space-id" homepage.js; then
  sed -i.bak \
    -e "s/your-space-id/${CONTENTFUL_SPACE_ID}/" \
    -e "s/your-delivery-api-token/${CONTENTFUL_ACCESS_TOKEN}/" \
    homepage.js && rm -f homepage.js.bak
  note "✓ updated Contentful config in homepage.js"
else
  note "homepage.js already updated, or placeholders not found — check it manually."
fi

# ── Stage 7: build + deploy the case-study app ─────────────────────────────
stage "Build case-study-app → commit static output"
say "One-time manual build (no CI, per your call earlier) — repeat this stage"
say "whenever you change case-study-app's code, NOT when you edit content in Contentful."
(cd case-study-app && npm install --silent && npm run build)
rm -rf case-study
cp -r case-study-app/dist case-study
note "✓ built into ./case-study"
git add -A
if confirm "Commit and push everything now?"; then
  git commit -m "Wire up Contentful space + deploy case-study app" || note "nothing to commit"
  git push
else
  note "skipped — review with 'git status' then commit/push yourself."
fi

# ── Stage 8: verify ─────────────────────────────────────────────────────────
stage "Verify — see it live"
say "Homepage's case-study grid will look empty until at least one Case Study"
say "entry exists AND is published — add one now if you haven't."
open_url "https://reynalddff.github.io/portfolio/"
open_url "https://app.contentful.com/spaces/${CONTENTFUL_SPACE_ID}/entries"
say "Once you've published an entry, test its detail page:"
note "  https://reynalddff.github.io/portfolio/case-study/?slug=<its-slug>"
pause "Press Enter when you've confirmed both pages load..."

finish
