#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

PORTFOLIO_DIR="/Users/reynalddaffa/Vibe Coding/My First Porto"
cd "$PORTFOLIO_DIR" || { echo "Can't find $PORTFOLIO_DIR"; exit 1; }
ENV_FILE="$PORTFOLIO_DIR/case-study-app/.env"

banner "Sanity-backed case studies — go live"

# ── Stage 1: GitHub repo ───────────────────────────────────────────────────
stage "GitHub repo — create + push"
say "Your code is committed locally but has no home on GitHub yet."
BRANCH_NAME="main"
ask BRANCH_NAME "Branch to push as (main/master):"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "gh is installed and logged in — this can create the repo and push in one step."
  if confirm "Create public repo reynalddff/portfolio and push now?"; then
    git branch -M "$BRANCH_NAME"
    gh repo create reynalddff/portfolio --public --source=. --remote=origin --push
  else
    note "skipped — do it manually later (see below)."
  fi
else
  step "Open https://github.com/new, owner=reynalddff, name=portfolio, Public, no README/gitignore/license."
  open_url "https://github.com/new"
  pause "Press Enter once the empty repo exists on GitHub..."
  git branch -M "$BRANCH_NAME"
  git remote add origin https://github.com/reynalddff/portfolio.git 2>/dev/null || git remote set-url origin https://github.com/reynalddff/portfolio.git
  if confirm "Push local history to origin/$BRANCH_NAME now?"; then
    git push -u origin "$BRANCH_NAME"
  else
    note "skipped — run: git push -u origin $BRANCH_NAME"
  fi
fi

# ── Stage 2: GitHub Pages ──────────────────────────────────────────────────
stage "GitHub Pages — enable"
say "Turns the repo into a live site at https://reynalddff.github.io/portfolio/"
open_url "https://github.com/reynalddff/portfolio/settings/pages"
step "Under 'Build and deployment' → Source, choose 'Deploy from a branch'."
step "Branch: $BRANCH_NAME, folder: / (root). Save."
pause "Press Enter once saved (first deploy takes ~1 min)..."

# ── Stage 3: Sanity Studio scaffold ────────────────────────────────────────
stage "Sanity Studio — scaffold project"
say "This creates your actual Sanity project (opens a browser login the first"
say "time), and generates the Studio app into ./studio. It asks its own"
say "questions — answer them like this:"
step "output path → studio"
step "project name → portfolio (or anything you like)"
step "use the default dataset configuration → yes, dataset name: production"
step "TypeScript → No"
step "template → Clean project with no predefined schema"
step "package manager → npm"
pause "Press Enter to launch it..."
npm create sanity@latest
say "Scaffold done. Now grab your project ID."
SANITY_PROJECT_ID=""
FOUND_ID=$(grep -hoE "projectId:\s*'[a-z0-9]+'" studio/sanity.config.* studio/sanity.cli.* 2>/dev/null | grep -oE "'[a-z0-9]+'" | tr -d "'" | head -n1 || true)
if [[ -n "$FOUND_ID" ]]; then
  note "found projectId in studio/sanity.config: $FOUND_ID"
fi
ask SANITY_PROJECT_ID "Sanity project ID${FOUND_ID:+ [Enter to use $FOUND_ID]}:"
[[ -z "$SANITY_PROJECT_ID" && -n "$FOUND_ID" ]] && SANITY_PROJECT_ID="$FOUND_ID"

# ── Stage 4: wire up the schema ────────────────────────────────────────────
stage "Schema — register caseStudy"
say "studio-schema/caseStudy.js has your case-study fields ready to go —"
say "it just needs to move into the Studio and get registered."
if [[ -d studio/schemaTypes ]]; then
  cp studio-schema/caseStudy.js studio/schemaTypes/caseStudy.js
  note "copied → studio/schemaTypes/caseStudy.js"
else
  warn "studio/schemaTypes not found — copy studio-schema/caseStudy.js there manually."
fi
say "Open studio/schemaTypes/index.js and make sure it imports and exports caseStudy, e.g.:"
note "  import caseStudy from './caseStudy'"
note "  export const schemaTypes = [caseStudy]"
pause "Press Enter once schemaTypes/index.js includes caseStudy..."
if confirm "Delete the now-empty studio-schema/ folder?"; then
  rm -rf studio-schema
fi

# ── Stage 5: deploy hosted Studio ──────────────────────────────────────────
stage "Studio — deploy hosted editor"
say "Publishes the content editor at <name>.sanity.studio — this is where"
say "you'll actually write case studies day to day."
pause "Press Enter to run 'sanity deploy' (answer its hostname prompt yourself)..."
(cd studio && npx sanity deploy)

# ── Stage 6: CORS ──────────────────────────────────────────────────────────
stage "CORS — allow your site to read Sanity"
say "Without this, fetch() calls from your site get blocked by the browser."
open_url "https://www.sanity.io/manage/project/${SANITY_PROJECT_ID}/api"
say "Add each origin below (Add CORS origin), 'Allow credentials' = No for all:"
step "http://localhost:8000   (homepage dev, python3 -m http.server)"
step "http://localhost:5173   (case-study-app dev, npm run dev)"
step "https://reynalddff.github.io"
pause "Press Enter once all three are added..."

# ── Stage 7: wire the project ID into the code ─────────────────────────────
stage "Project ID — wire into the app + homepage"
write_env "VITE_SANITY_PROJECT_ID" "$SANITY_PROJECT_ID"
write_env "VITE_SANITY_DATASET" "production"
say "homepage.js has no build step, so its Sanity config is a plain string —"
say "safe to edit directly (projectId/dataset aren't secrets)."
if grep -q "your-project-id" homepage.js; then
  sed -i.bak "s/your-project-id/${SANITY_PROJECT_ID}/" homepage.js && rm -f homepage.js.bak
  note "✓ updated SANITY_PROJECT_ID in homepage.js"
else
  note "homepage.js already updated, or placeholder not found — check it manually."
fi

# ── Stage 8: build + deploy the case-study app ─────────────────────────────
stage "Build case-study-app → commit static output"
say "One-time manual build (no CI, per your call earlier) — repeat this stage"
say "whenever you change case-study-app's code, NOT when you edit content in Studio."
(cd case-study-app && npm install --silent && npm run build)
rm -rf case-study
cp -r case-study-app/dist case-study
note "✓ built into ./case-study"
git add -A
if confirm "Commit and push everything now?"; then
  git commit -m "Wire up Sanity project + deploy case-study app" || note "nothing to commit"
  git push
else
  note "skipped — review with 'git status' then commit/push yourself."
fi

# ── Stage 9: verify ─────────────────────────────────────────────────────────
stage "Verify — see it live"
say "Homepage's case-study grid will look empty until at least one caseStudy"
say "document exists — add one now in Studio if you haven't."
open_url "https://reynalddff.github.io/portfolio/"
open_url "https://www.sanity.io/manage/project/${SANITY_PROJECT_ID}/api"
say "Once you've published a document, test its detail page:"
note "  https://reynalddff.github.io/portfolio/case-study/?slug=<its-slug>"
pause "Press Enter when you've confirmed both pages load..."

finish
